export const Channels = {
  getAppVersion: "app:getVersion",

  selectRepository: "repo:select",
  selectDirectory: "repo:selectDirectory",
  cloneRepository: "repo:clone",
  initRepository: "repo:init",
  getRecentRepositories: "repo:recent",

  getStatus: "git:status",
  getDiff: "git:diff",
  stageFile: "git:stageFile",
  unstageFile: "git:unstageFile",
  stageAll: "git:stageAll",
  unstageAll: "git:unstageAll",
  discardFile: "git:discardFile",
  discardAll: "git:discardAll",
  commit: "git:commit",
  getHistory: "git:history",
  getFileHistory: "git:fileHistory",
  getCommitDetails: "git:commitDetails",
  getCommitFileDiff: "git:commitFileDiff",
  getFileContent: "git:fileContent",
  getSplitContent: "git:splitContent",
  getBranches: "git:branches",
  getTags: "git:tags",
  checkoutBranch: "git:checkoutBranch",
  checkoutRemoteBranch: "git:checkoutRemoteBranch",
  createBranch: "git:createBranch",
  createTag: "git:createTag",
  pushTag: "git:pushTag",
  deleteBranch: "git:deleteBranch",
  renameBranch: "git:renameBranch",
  mergeBranch: "git:mergeBranch",
  pull: "git:pull",
  push: "git:push",
  cherryPick: "git:cherryPick",
  continueCherryPick: "git:continueCherryPick",
  abortCherryPick: "git:abortCherryPick",
  revertCommit: "git:revertCommit",
  stashList: "git:stashList",
  stashPush: "git:stashPush",
  stashPop: "git:stashPop",
  stashApply: "git:stashApply",
  stashDrop: "git:stashDrop",
  watchRepository: "git:watchRepository",
  unwatchRepository: "git:unwatchRepository",
  repositoryChanged: "git:repositoryChanged",

  isVSCodeAvailable: "editor:isVSCodeAvailable",
  openFileInVSCode: "editor:openFileInVSCode",
  openRepoInVSCode: "editor:openRepoInVSCode",

  terminalCreate: "terminal:create",
  terminalInput: "terminal:input",
  terminalResize: "terminal:resize",
  terminalClose: "terminal:close",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",

  worktreeList: "worktree:list",
  worktreeCreate: "worktree:create",
  worktreeDelete: "worktree:delete",
  worktreeMove: "worktree:move",
  worktreePrune: "worktree:prune",
  worktreeOpenInFinder: "worktree:openInFinder",
  worktreeSwitch: "worktree:switch"
} as const;
